export const fortunes = [
  "A cookie a day keeps the sadness away.",
  "Your future is as sweet as chocolate chips.",
  "Good things come to those who bake.",
  "The best cookies are made with love.",
  "You will find happiness in small, round packages.",
  "A crumb of wisdom: share your cookies.",
  "Your kindness is like warm cookies - it spreads joy.",
  "The secret ingredient is always patience.",
  "Sweet dreams are made of cookie dough.",
  "You are one smart cookie!",
  "Life is what you bake it.",
  "Every cookie tells a story.",
  "The sweetest victories come after the hardest work.",
  "You have the recipe for success.",
  "Sprinkle kindness wherever you go.",
  "The best things in life are homemade.",
  "You are the chocolate chip in someone's cookie.",
  "Fresh starts are like fresh cookies - full of potential.",
  "Your creativity knows no bounds, like cookie flavors.",
  "The warmth you give others will return to you tenfold.",
]
